channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake=7.16.0
  - python=3.9
  - pandas=1.3.2
  - cutadapt=3.5
  - bwa=0.7.17
  - samtools
  - gatk4=4.1.9.0  
  - lofreq=2.1.5
  - scalpel
  - bamtools=2.5.1
  - pip
  - pip:
    - vatools
